name: Feature request triage bot

on:
  schedule:
    # Run at 15:00 every day
    - cron: '0 15 * * *'

jobs:
  feature_triage:
    if: github.repository == 'angular/components'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/feature-request@138ec743c342cd2a4a75443d19e0ccd47244ee07
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
